#!/bin/bash
# ensure that the python3 bits are installed, whichever version of ubunut
# is being installed.

declare -a DEPS=('apt' 'netaddr' 'netifaces' 'pip' 'yaml')

check_and_install() {
    pkg="${1}-${2}"
    if ! dpkg -s ${pkg} 2>&1 > /dev/null; then
        apt-get -y install ${pkg}
    fi
}

PYTHON="python3"

for dep in ${DEPS[@]}; do
    check_and_install ${PYTHON} ${dep}
done

./hooks/install_deps
exec ./hooks/install.real
