#!/usr/bin/python

"""Amulet tests on a basic ceph-radosgw deployment on trusty-juno."""

from basic_deployment import CephRadosGwBasicDeployment

if __name__ == '__main__':
    deployment = CephRadosGwBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-juno',
                                     source='cloud:trusty-updates/juno')
    deployment.run_tests()
