#!/usr/bin/python

"""Amulet tests on a basic ceph-radosgw deployment on trusty-kilo."""

from basic_deployment import CephRadosGwBasicDeployment

if __name__ == '__main__':
    deployment = CephRadosGwBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-kilo',
                                     source='cloud:trusty-updates/kilo')
    deployment.run_tests()
