#!/usr/bin/python

"""Amulet tests on a basic ceph-radosgw deployment on trusty-liberty."""

from basic_deployment import CephRadosGwBasicDeployment

if __name__ == '__main__':
    deployment = CephRadosGwBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-liberty',
                                     source='cloud:trusty-updates/liberty')
    deployment.run_tests()
