#!/usr/bin/python

"""Amulet tests on a basic ceph-radosgw deployment on trusty-mitaka."""

from basic_deployment import CephRadosGwBasicDeployment

if __name__ == '__main__':
    deployment = CephRadosGwBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-mitaka',
                                     source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
