#!/usr/bin/python

"""Amulet tests on a basic ceph-radosgw deployment on xenial-mitaka."""

from basic_deployment import CephRadosGwBasicDeployment

if __name__ == '__main__':
    deployment = CephRadosGwBasicDeployment(series='xenial')
    deployment.run_tests()
