#!/usr/bin/python

"""Amulet tests on a basic ceph-radosgw deployment on precise-icehouse."""

from basic_deployment import CephRadosGwBasicDeployment

if __name__ == '__main__':
    deployment = CephRadosGwBasicDeployment(series='precise',
                                     openstack='cloud:precise-icehouse',
                                     source='cloud:precise-updates/icehouse')
    deployment.run_tests()
