#!/usr/bin/python

"""Amulet tests on a basic ceph-radosgw deployment on trusty-icehouse."""

from basic_deployment import CephRadosGwBasicDeployment

if __name__ == '__main__':
    deployment = CephRadosGwBasicDeployment(series='trusty')
    deployment.run_tests()
