#!/usr/bin/python

"""Amulet tests on a basic ceph-osd deployment on trusty-juno."""

from basic_deployment import CephOsdBasicDeployment

if __name__ == '__main__':
    deployment = CephOsdBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-juno',
                                     source='cloud:trusty-updates/juno')
    deployment.run_tests()
