#!/usr/bin/python

"""Amulet tests on a basic ceph-osd deployment on trusty-kilo."""

from basic_deployment import CephOsdBasicDeployment

if __name__ == '__main__':
    deployment = CephOsdBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-kilo',
                                     source='cloud:trusty-updates/kilo')
    deployment.run_tests()
