#!/usr/bin/python

"""Amulet tests on a basic ceph-osd deployment on utopic-juno."""

from basic_deployment import CephOsdBasicDeployment

if __name__ == '__main__':
    deployment = CephOsdBasicDeployment(series='utopic')
    deployment.run_tests()
