#!/usr/bin/python

"""Amulet tests on a basic ceph-osd deployment on trusty-liberty."""

from basic_deployment import CephOsdBasicDeployment

if __name__ == '__main__':
    deployment = CephOsdBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-liberty',
                                     source='cloud:trusty-updates/liberty')
    deployment.run_tests()
