#!/usr/bin/python

"""Amulet tests on a basic ceph-osd deployment on trusty-mitaka."""

from basic_deployment import CephOsdBasicDeployment

if __name__ == '__main__':
    deployment = CephOsdBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-mitaka',
                                     source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
