#!/usr/bin/python

"""Amulet tests on a basic ceph-osd deployment on vivid-kilo."""

from basic_deployment import CephOsdBasicDeployment

if __name__ == '__main__':
    deployment = CephOsdBasicDeployment(series='vivid')
    deployment.run_tests()
