#!/usr/bin/python

"""Amulet tests on a basic ceph-osd deployment on wily-liberty."""

from basic_deployment import CephOsdBasicDeployment

if __name__ == '__main__':
    deployment = CephOsdBasicDeployment(series='wily')
    deployment.run_tests()
