#!/usr/bin/python

"""Amulet tests on a basic ceph-osd deployment on precise-icehouse."""

from basic_deployment import CephOsdBasicDeployment

if __name__ == '__main__':
    deployment = CephOsdBasicDeployment(series='precise',
                                     openstack='cloud:precise-icehouse',
                                     source='cloud:precise-updates/icehouse')
    deployment.run_tests()
