#!/usr/bin/python

"""Amulet tests on a basic ceph-osd deployment on trusty-icehouse."""

from basic_deployment import CephOsdBasicDeployment

if __name__ == '__main__':
    deployment = CephOsdBasicDeployment(series='trusty')
    deployment.run_tests()
