#!/bin/bash -e

# Wrapper to ensure that old python bytecode isn't hanging around
# after we upgrade the charm with newer libraries
find . -iname '*.pyc' -delete
find . -name '__pycache__' -prune -exec rm -rf "{}" \;

# Re-install dependencies to deal with py2->py3 switch for charm
./hooks/install_deps

./hooks/upgrade-charm.real
